#!/usr/bin/bash

echo "Setting up environment..."

# link files - bash
echo "Linking bash files..."
rm $HOME/.bash_profile
ln -s $PWD/bash/.bash_profile $HOME/.bash_profile
rm $HOME/.bashrc
ln -s $PWD/bash/.bashrc $HOME/.bashrc
echo "Done with bash files."

# link files - emacs
echo "Linking emacs files..."
rm $HOME/.emacs
ln -s $PWD/emacs/.emacs $HOME/.emacs
mkdir -p $HOME/.config/systemd/user
rm $HOME/.config/systemd/user/emacs.service
ln -s $PWD/emacs/emacs.service $HOME/.config/systemd/user/emacs.service
echo "Done with emacs files."

# link files - gdb
echo "Linking gdb files..."
rm $HOME/.gdbinit
ln -s $PWD/gdb/.gdbinit $HOME/.gdbinit
echo "Done with gdb files."

# link files - git
echo "Linking git files..."
rm $HOME/.gitconfig
ln -s $PWD/git/.gitconfig $HOME/.gitconfig
rm $HOME/.gitignore
ln -s $PWD/git/.gitignore $HOME/.gitignore
echo "Done with git files."

# link files - lynx
echo "Linking lynx files..."
rm $HOME/.lynxrc
ln -s $PWD/lynx/.lynxrc $HOME/.lynxrc
echo "Done with lynx files."

# link files - mpv
echo "Linking mpv files..."
rm $HOME/.config/mpv/mpv.conf
ln -s $PWD/mpv/mpv.conf $HOME/.config/mpv/mpv.conf
echo "Done with mpv files."

# link files - tmux
echo "Linking tmux files..."
rm $HOME/.tmux.conf
ln -s $PWD/tmux/.tmux.conf $HOME/.tmux.conf
echo "Done with tmux files."

# link files - vim
echo "Linking vim files..."
rm $HOME/.vimrc
ln -s $PWD/vim/.vimrc $HOME/.vimrc
echo "Done with vim files."

# link files - x-server
echo "Linking x-server files..."
rm $HOME/.Xdefaults
ln -s $PWD/x-server/.Xdefaults $HOME/.Xdefaults
echo "Done with x-server files."

# link files - containers
echo "Linking container registries file..."
rm -rf $HOME/.config/containers/
mkdir $HOME/.config/containers
ln -s $PWD/containers/registries.conf $HOME/.config/containers/registries.conf
echo "Done with container registries file..."

echo "Done setting up the evironment. God speed and happy computing!!!"
