#!/usr/bin/perl

use strict;
use warnings;

my $HOME = $ENV{"HOME"};
my $PWD = $ENV{"PWD"};

print "Setting up environment...\n";

# link files - bash
print "Linking bash files...\n";
system "rm $HOME/.bash_profile";
system "ln -s $PWD/bash/.bash_profile $HOME/.bash_profile";
system "rm $HOME/.bashrc";
system "ln -s $PWD/bash/.bashrc $HOME/.bashrc"; 
print "Done with bash files.\n";

# link files - emacs
print "Linking emacs files...\n";
system "rm $HOME/.emacs";
system "ln -s $PWD/emacs/.emacs $HOME/.emacs";
system "mkdir -p $HOME/.config/systemd/user";
system "rm $HOME/.config/systemd/user/emacs.service";
system "ln -s $PWD/emacs/emacs.service $HOME/.config/systemd/user/emacs.service";
print "Done with emacs files.\n";

# link files - gdb
print "Linking gdb files...\n";
system "rm $HOME/.gdbinit";
system "ln -s $PWD/gdb/.gdbinit $HOME/.gdbinit";
print "Done with gdb files.\n";

# link files - git
print "Linking git files...\n";
system "rm $HOME/.gitconfig";
system "ln -s $PWD/git/.gitconfig $HOME/.gitconfig";
system "rm $HOME/.gitignore";
system "ln -s $PWD/git/.gitignore $HOME/.gitignore";
print "Done with git files.\n";

# link files - irssi
print "Linking irssi files...\n";

print "Done with irssi files.\n";

# link files - lynx
print "Linking lynx files...\n";

print "Done with lynx files.\n";

# link files - mpv
print "Linking mpv files...\n";
system "rm $HOME/.config/mpv/mpv.conf";
system "ln -s $PWD/mpv/mpv.conf $HOME/.config/mpv/mpv.conf";
print "Done with mpv files.\n";


# link files - tmux
print "Linking tmux files...\n";
system "rm $HOME/.tmux.conf";
system "ln -s $PWD/tmux/.tmux.conf $HOME/.tmux.conf";
print "Done with tmux files.\n";

# link files - vim
print "Linking vim files...\n";
system "rm $HOME/.vimrc";
system "ln -s $PWD/vim/.vimrc $HOME/.vimrc";
print "Done with vim files.\n";


# link files - x-server
print "Linking x-server files...\n";
system "rm $HOME/.Xdefaults";
system "ln -s $PWD/x-server/.Xdefaults $HOME/.Xdefaults";
print "Done with x-server files.\n";


print "Done setting up evironment. God speed and Happy computing!\n";
