(defun insert-perl-template ()
  "Inserts a basic Perl script template."
  (interactive)
  (insert "#!/usr/bin/perl\n")
  (insert "use strict;\n")
  (insert "use warnings;\n")
  (insert "use feature 'say';\n")
  (insert "\n")
  (insert "\"\"\"\n")
  (insert "A brief description of the script's purpose.\n")
  (insert "\"\"\"\n")
  (insert "\n")
  (insert "sub main {\n")
  (insert "    print('Hello, world!');\n")
  (insert "}\n")
  (insert "\n")
  (insert "exit(main(@ARGV));"))
