(defun insert-python-template ()
  "Inserts a basic Python script template."
  (interactive)
  (insert "#!/usr/bin/python\n")
  (insert "\n")
  (insert "\"\"\"\n")
  (insert "A brief description of the script's purpose.\n")
  (insert "\"\"\"\n")
  (insert "\n")
  (insert "def main():\n")
  (insert "    print('Hello, world!')\n")
  (insert "\n")
  (insert "if __name__ == '__main__':\n")
  (insert "    main()\n"))
